services:
  mysql:
    image: mysql:8.0
    container_name: base-project-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_base_auth
      MYSQL_ROOT_PASSWORD: 123456
      LANG: C.UTF-8
    ports:
      - "3311:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - base-project-service
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  base-project-service:
    driver: bridge

volumes:
  mysql-data: